version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: quickrent-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quickrent
      POSTGRES_USER: quickrent
      POSTGRES_PASSWORD: quickrent
    ports:
      - '5432:5432'
    volumes:
      - quickrent_pg_data:/var/lib/postgresql/data

volumes:
  quickrent_pg_data:
