// ============================================================================
// OMNI-RESILIENT GLOBAL LIFESTYLE OS
// Multi-Language Support (Localization)
// ============================================================================

class AppLocalization {
  static final Map<String, Map<String, String>> _translations = {
    'ar': {
      'app_name': 'أومني رينت',
      'home': 'الرئيسية',
      'search': 'بحث',
      'book': 'احجز',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'properties': 'العقارات',
      'rides': 'النقل',
      'food': 'التوصيل',
      'travel': 'السفر',
      'health': 'الصحة',
      'delivery': 'خدمات التوصيل',
      'hotel_services': 'الخدمات المجانية',
      'services': 'الخدمات',
      'select_date': 'اختر التاريخ',
      'select_time': 'اختر الوقت',
      'select_location': 'اختر الموقع',
      'book_now': 'احجز الآن',
      'view_details': 'عرض التفاصيل',
      'pending': 'قيد الانتظار',
      'confirmed': 'تم التأكيد',
      'in_progress': 'قيد التنفيذ',
      'completed': 'مكتمل',
      'national_address': 'العنوان الوطني',
      'price': 'السعر',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'area': 'المساحة',
      'rating': 'التقييم',
      'favorites': 'المفضلة',
      'my_bookings': 'حجوزاتي',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'english': 'English',
      'arabic': 'العربية',
      'french': 'Français',
      'german': 'Deutsch',
      'japanese': '日本語',
    },
    'en': {
      'app_name': 'OmniRent',
      'home': 'Home',
      'search': 'Search',
      'book': 'Book',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'properties': 'Properties',
      'rides': 'Rides',
      'food': 'Food',
      'travel': 'Travel',
      'health': 'Health',
      'delivery': 'Delivery Services',
      'hotel_services': 'Free Services',
      'services': 'Services',
      'select_date': 'Select Date',
      'select_time': 'Select Time',
      'select_location': 'Select Location',
      'book_now': 'Book Now',
      'view_details': 'View Details',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'in_progress': 'In Progress',
      'completed': 'Completed',
      'national_address': 'National Address',
      'price': 'Price',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'area': 'Area',
      'rating': 'Rating',
      'favorites': 'Favorites',
      'my_bookings': 'My Bookings',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Logout',
      'language': 'Language',
      'english': 'English',
      'arabic': 'العربية',
      'french': 'Français',
      'german': 'Deutsch',
      'japanese': '日本語',
    },
    'fr': {
      'app_name': 'OmniRent',
      'home': 'Accueil',
      'search': 'Rechercher',
      'book': 'Réserver',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'properties': 'Propriétés',
      'rides': 'Trajets',
      'food': 'Nourriture',
      'travel': 'Voyage',
      'health': 'Santé',
      'delivery': 'Services de Livraison',
      'hotel_services': 'Services Gratuits',
      'services': 'Services',
      'select_date': 'Sélectionner la date',
      'select_time': 'Sélectionner l\'heure',
      'select_location': 'Sélectionner le lieu',
      'book_now': 'Réserver maintenant',
      'view_details': 'Voir les détails',
      'pending': 'En attente',
      'confirmed': 'Confirmé',
      'in_progress': 'En cours',
      'completed': 'Terminé',
      'national_address': 'Adresse nationale',
      'price': 'Prix',
      'bedrooms': 'Chambres',
      'bathrooms': 'Salles de bains',
      'area': 'Superficie',
      'rating': 'Évaluation',
      'favorites': 'Favoris',
      'my_bookings': 'Mes réservations',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'logout': 'Déconnexion',
      'language': 'Langue',
      'english': 'English',
      'arabic': 'العربية',
      'french': 'Français',
      'german': 'Deutsch',
      'japanese': '日本語',
    },
    'de': {
      'app_name': 'OmniRent',
      'home': 'Startseite',
      'search': 'Suchen',
      'book': 'Buchen',
      'confirm': 'Bestätigen',
      'cancel': 'Abbrechen',
      'properties': 'Immobilien',
      'rides': 'Fahrten',
      'food': 'Essen',
      'travel': 'Reisen',
      'health': 'Gesundheit',
      'delivery': 'Lieferservices',
      'hotel_services': 'Kostenlose Dienstleistungen',
      'services': 'Dienstleistungen',
      'select_date': 'Datum auswählen',
      'select_time': 'Zeit auswählen',
      'select_location': 'Standort auswählen',
      'book_now': 'Jetzt buchen',
      'view_details': 'Details anzeigen',
      'pending': 'Ausstehend',
      'confirmed': 'Bestätigt',
      'in_progress': 'Laufend',
      'completed': 'Abgeschlossen',
      'national_address': 'Nationale Adresse',
      'price': 'Preis',
      'bedrooms': 'Schlafzimmer',
      'bathrooms': 'Badezimmer',
      'area': 'Fläche',
      'rating': 'Bewertung',
      'favorites': 'Favoriten',
      'my_bookings': 'Meine Buchungen',
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'logout': 'Abmelden',
      'language': 'Sprache',
      'english': 'English',
      'arabic': 'العربية',
      'french': 'Français',
      'german': 'Deutsch',
      'japanese': '日本語',
    },
    'ja': {
      'app_name': 'オムニレント',
      'home': 'ホーム',
      'search': '検索',
      'book': '予約',
      'confirm': '確認',
      'cancel': 'キャンセル',
      'properties': 'プロパティ',
      'rides': '乗車',
      'food': '食品',
      'travel': '旅行',
      'health': '健康',
      'delivery': '配送サービス',
      'hotel_services': '無料サービス',
      'services': 'サービス',
      'select_date': '日付を選択',
      'select_time': '時刻を選択',
      'select_location': '場所を選択',
      'book_now': '今予約',
      'view_details': '詳細を表示',
      'pending': '保留中',
      'confirmed': '確認済み',
      'in_progress': '進行中',
      'completed': '完了',
      'national_address': '国の住所',
      'price': '価格',
      'bedrooms': 'ベッドルーム',
      'bathrooms': 'バスルーム',
      'area': '面積',
      'rating': '評価',
      'favorites': 'お気に入り',
      'my_bookings': '私の予約',
      'profile': 'プロフィール',
      'settings': '設定',
      'logout': 'ログアウト',
      'language': '言語',
      'english': 'English',
      'arabic': 'العربية',
      'french': 'Français',
      'german': 'Deutsch',
      'japanese': '日本語',
    },
  };

  /// Get translated text
  static String get(String key, {String languageCode = 'en'}) {
    return _translations[languageCode]?[key] ?? _translations['en']?[key] ?? key;
  }

  /// Get all translations for a language
  static Map<String, String> getAll(String languageCode) {
    return _translations[languageCode] ?? _translations['en']!;
  }

  /// Supported languages
  static List<String> getSupportedLanguages() {
    return _translations.keys.toList();
  }
}
